console-startup-message: |-
  &r
  &r
  &r   &f&m---------------------------------------------------
  &r      &fEnderButt &bhas been enabled successfully!
  &r      &fAuthor: &bEmmiesa
  &r      &fVersion: &b1.0-SNAPPYSHOT
  &r   &f&m---------------------------------------------------
  &r

console-shutdown-message: "&e[&dEnderButt&e] &7Plugin has been disabled!"

enderbutt:
  enabled: true
  type: "RIDE" #RIDE, FOLLOW
  sound_enabled: true
  sound: ENDERMAN_TELEPORT
  effect-ride:
    enable: true
    effect: HEART
